# Job to run canary test
apiVersion: batch/v1
kind: Job
metadata:
  name: canary-test
  namespace: ecommerce
spec:
  template:
    metadata:
      labels:
        app: canary-test
    spec:
      containers:
      - name: test
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          apk add --no-cache bash
          chmod +x /scripts/test-canary.sh
          /scripts/test-canary.sh
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: scripts
        configMap:
          name: canary-test-script
  backoffLimit: 1